name: Build PSP Game

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PSPDEV
        run: |
          git clone --depth 1 https://github.com/pspdev/pspdev.git
          cd pspdev
          ./prepare.sh
